-- MySQL Script generated by MySQL Workbench
-- Wed Jul 16 14:28:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reservations-coworking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservations-coworking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservations-coworking` DEFAULT CHARACTER SET utf8 ;
USE `reservations-coworking` ;

-- -----------------------------------------------------
-- Table `reservations-coworking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservations-coworking`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email_user` VARCHAR(200) NOT NULL,
  `password_hash_user` VARCHAR(255) NOT NULL,
  `last_name_user` VARCHAR(100) NOT NULL,
  `first_name_user` VARCHAR(100) NOT NULL,
  `role_user` ENUM('membre', 'gestionnaire', 'admin') NOT NULL,
  `created_at_user` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_user_UNIQUE` (`email_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservations-coworking`.`spaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservations-coworking`.`spaces` (
  `id_space` INT NOT NULL AUTO_INCREMENT,
  `name_space` VARCHAR(100) NOT NULL,
  `capacity_space` INT NOT NULL,
  `equipement_space` TEXT NULL,
  `type_space` ENUM('bureau', 'salle') NOT NULL,
  PRIMARY KEY (`id_space`),
  UNIQUE INDEX `name_space_UNIQUE` (`name_space` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservations-coworking`.`timeslots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservations-coworking`.`timeslots` (
  `id_timeslot` INT NOT NULL AUTO_INCREMENT,
  `fk_id_space` INT NOT NULL,
  `start_time_timeslot` DATETIME NOT NULL,
  `en_time_timeslot` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id_timeslot`),
  INDEX `fk_id_space_idx` (`fk_id_space` ASC) VISIBLE,
  INDEX `created_by_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_id_space`
    FOREIGN KEY (`fk_id_space`)
    REFERENCES `reservations-coworking`.`spaces` (`id_space`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `reservations-coworking`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservations-coworking`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservations-coworking`.`reservations` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `fk_id_user` INT NOT NULL,
  `fk_id_timeslot` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id_reservation`),
  INDEX `fk_id_user_idx` (`fk_id_user` ASC) VISIBLE,
  INDEX `fk_id_timeslot_idx` (`fk_id_timeslot` ASC) VISIBLE,
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `reservations-coworking`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_timeslot`
    FOREIGN KEY (`fk_id_timeslot`)
    REFERENCES `reservations-coworking`.`timeslots` (`id_timeslot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insertion de données 
-- -----------------------------------------------------
-- users
insert into users (email_user, password_hash_user, last_name_user, first_name_user, role_user, created_at_user) values ('hdemanche0@cnet.com', '$2a$04$U3yyiJFSkgHcdJzjExVPTOuAJJESHn94O8RdNjopzWPgK2gIP2vsy', 'Demanche', 'Hanny', 'membre', '2006/08/29');
insert into users (email_user, password_hash_user, last_name_user, first_name_user, role_user, created_at_user) values ('cvernazza1@nasa.gov', '$2a$04$UfXzwMF5rDKehJ7oIImrn.exshjR/JNf/CzTaB1STxkjzWUHBb0.K', 'Vernazza', 'Clarice', 'gestionnaire', '2022/11/01');
insert into users (email_user, password_hash_user, last_name_user, first_name_user, role_user, created_at_user) values ('ahincks2@live.com', '$2a$04$/50pq4dJ9DTufzh4BlF1DuzGaUtqB5PqA4OtVeA9gG9KHNgu0MVhG', 'Hincks', 'Avram', 'admin', '2014/02/28');

-- spaces
insert into spaces (name_space, capacity_space, equipement_space, type_space) values ('Jobye', 13, '', 'bureau');
insert into spaces (name_space, capacity_space, equipement_space, type_space) values ('Paton', 26, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'salle');
insert into spaces (name_space, capacity_space, equipement_space, type_space) values ('Phaedra', 39, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'bureau');
insert into spaces (name_space, capacity_space, equipement_space, type_space) values ('Paolina', 97, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'bureau');

-- timeslots
insert into timeslots (fk_id_space, start_time_timeslot, en_time_timeslot, created_by) values (4, '2025-11-16 11:00:00', '2025-11-16 20:00:00', 2);
insert into timeslots (fk_id_space, start_time_timeslot, en_time_timeslot, created_by) values (3, '2025-11-14 10:00:00', '2025-11-14 17:00:00', 2);
insert into timeslots (fk_id_space, start_time_timeslot, en_time_timeslot, created_by) values (3, '2025-08-31 11:30:00', '2025-08-31 21:30:00', 2);
insert into timeslots (fk_id_space, start_time_timeslot, en_time_timeslot, created_by) values (2, '2025-09-15 01:00:00', '2025-09-15 10:00:00', 2);
insert into timeslots (fk_id_space, start_time_timeslot, en_time_timeslot, created_by) values (4, '2025-11-30 22:30:00', '2025-11-30 23:30:00', 2);
insert into timeslots (fk_id_space, start_time_timeslot, en_time_timeslot, created_by) values (2, '2025-11-02 00:00:00', '2025-11-02 07:30:00', 2);

-- reservations
insert into reservations (fk_id_user, fk_id_timeslot, created_at) values (1, 1, '2025-04-17 00:11:50');
insert into reservations (fk_id_user, fk_id_timeslot, created_at) values (1, 6, '2025-07-12 10:20:27');